---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.17.7
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 1Gi
            cpu: 1000m
        ports:
          - containerPort: 5044
        env:
        - name: LS_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        volumeMounts:
        - name: logstash-config
          mountPath: "/usr/share/logstash/config"
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-config
      - name: elasticsearch-secret
        secret:
          secretName: elasticsearch-secret

---
kind: Service
apiVersion: v1
metadata:
  name: logstash
spec:
  ports:
    - name: logstash
      protocol: TCP
      port: 10000
      targetPort: 9600
    - name: filebeat
      protocol: TCP
      port: 5044
      targetPort: 5044
  selector:
    app: logstash
  type: LoadBalancer
  sessionAffinity: None

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: default
data:
  logstash.yml: |-
    http.host: "0.0.0.0"
    path.data: /usr/share/logstash/data
    path.logs: /var/log/logstash
    path.work: /var/lib/logstash
    config.reload.automatic: true
    pipeline.workers: 1
    pipeline.batch.size: 125
    pipeline.batch.delay: 50
    pipeline.max_inflight: 10000
    pipeline.reload.interval: 15
    pipeline.reload.timeout: 60
    pipeline.config.reload.response.timeout: 1
    pipeline.config.path: /usr/share/logstash/pipeline
    pipeline.config.reload.enabled: true
    pipeline.config.reload.dirwatch.poll_interval: 5
    pipeline.config.reload.dirwatch.enabled: true
    pipeline.config.reload.http.enabled: true
    pipeline.config.reload.http.host: "localhost"
    pipeline.config.reload.http.port: 7070
    pipeline.config.reload.http.ssl.enabled: false
    xpack.monitoring.elasticsearch.username: ["${elastic_username}"]
    xpack.monitoring.elasticsearch.password: ["${elastic_password}"]
vars:
  - name: elastic_username
    secretValue: 
      name: elastic-credentials
      key: username
  - name: elastic_password
    secretValue: 
      name: elastic-credentials
      key: password