apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: k3s-data
  resources:
    requests:
      storage: 2Gi